# -*- coding: utf-8 -*-
"""Zakiyuddin Rahman-0110220215-TI05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4MWPFt8JM301_n-v-YXE42k53_uraoA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

col_name = ['Sample Code Number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitosses', 'Class' ]
df =  pd.read_csv('breast-cancer-wisconsin.data', sep=",", names=col_name) #Parameter Header berfungsi untuk melindungi data yang tidak ada headernya, agar data teratas tidak dianggap sebagai header
data = pd.DataFrame(df)
print(data)

data.info()

data.head()

data['Class'] = data['Class'].apply(str)
data.dtypes

data['Class'].replace('2', 'Benign', inplace=True)
data['Class'].replace('4', 'Malignant', inplace=True)
print(data)

data.isnull().sum()

data = data.drop(columns=['Sample Code Number'], axis=0)

data.head()

data.describe().plot(kind = "area",fontsize=20, figsize = (25,10), table = True,colormap="Pastel1")
plt.xlabel('Statistik')
plt.ylabel('Nilai')
plt.title("General Statistics of Dataset Breast Cancer Wisconsin")

sns.countplot ('Class', data=data)
plt.show()

data['Class'].value_counts().plot.pie(fontsize= 20, explode=[0.0075,0.0075], autopct='%1.1f%%', figsize=(20,15))
plt.show()

fig=sns.jointplot(x='Uniformity of Cell Size', y='Uniformity of Cell Shape', data=data)

fig2=sns.jointplot(x='Uniformity of Cell Size', y='Uniformity of Cell Shape', data=data, kind="reg")

fig3=sns.jointplot(x='Uniformity of Cell Size', y='Uniformity of Cell Shape', data=data, kind="hex")

sns.jointplot(x='Uniformity of Cell Size', y='Uniformity of Cell Shape', data=data, kind="kde", space=1, color='b')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
sns.FacetGrid(data, hue='Class', size=7)\
              .map(plt.scatter, 'Uniformity of Cell Size', 'Uniformity of Cell Shape')\
              .add_legend()

